VERSION 0.8

zig:
  ARG zig_version="0.13.0"
  ARG TARGETARCH
  FROM ubuntu:noble
  RUN apt update
  RUN apt install -y wget xz-utils
  IF [ $TARGETARCH = "aarch64" ] || [ $TARGETARCH = "arm64" ]
    RUN wget -O zig.tar.xz https://ziglang.org/download/$zig_version/zig-linux-aarch64-$zig_version.tar.xz
  ELSE IF [ $TARGETARCH = "x86_64" ] || [ $TARGETARCH = "amd64" ]
    RUN wget -O zig.tar.xz https://ziglang.org/download/$zig_version/zig-linux-x86_64-$zig_version.tar.xz
  ELSE
    RUN echo "Unsupported architecture: $TARGETARCH"
    RUN exit 1
  END
  RUN tar -xf zig.tar.xz
  RUN rm zig.tar.xz
  RUN mv zig* zig
  SAVE ARTIFACT zig
