VERSION 0.8

zig:
  ARG TARGETARCH
  FROM ubuntu:jammy
  RUN apt update
  RUN apt install -y wget xz-utils
  IF [ $TARGETARCH = "aarch64" ] || [ $TARGETARCH = "arm64" ]
    RUN wget -O zig.tar.xz https://ziglang.org/download/0.10.1/zig-linux-aarch64-0.10.1.tar.xz
  ELSE IF [ $TARGETARCH = "x86_64" ] || [ $TARGETARCH = "amd64" ]
    RUN wget -O zig.tar.xz https://ziglang.org/download/0.10.1/zig-linux-x86_64-0.10.1.tar.xz
  ELSE
    RUN echo "Unsupported architecture: $TARGETARCH"
    RUN exit 1
  END
  RUN tar -xf zig.tar.xz
  RUN rm zig.tar.xz
  RUN mv zig* zig
  SAVE ARTIFACT zig
